version: "3.8"
services:
  builder:
    build: .
    command:
      - /bin/bash
      - -c
      - /home/no_root/.cargo/bin/cargo build --manifest-path src/Cargo.toml --target-dir compiled
    volumes:
      - type: bind
        source: ../src/
        target: /home/no_root/src/
      - type: bind
        source: ../compiled/
        target: /home/no_root/compiled/