FROM ubuntu@sha256:ca5534a51dd04bbcebe9b23ba05f389466cf0c190f1f8f182d7eea92a9671d00

RUN apt update && apt upgrade -y&& apt install -y curl build-essential && apt autoremove -y;

RUN useradd no_root --create-home;
WORKDIR /home/no_root

USER no_root
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > rustup.sh && sh rustup.sh -y --profile minimal;

RUN rm rustup.sh;

USER root
RUN apt purge -y curl build-essential;
RUN apt clean;

USER no_root
#CMD ["/home/no_root/.cargo/bin/cargo","build","--manifest-path","src/Cargo.toml","--target-dir","compiled"]