[package]
name = "FTP"
version = "0.1.0"
authors = ["me"]
edition = "2021"

[[bin]]
name = "ftp"
path = "main.rs"

[dependencies]
regex = "1.6.0"
dotenv = "0.15.0"
dotenv_codegen = "0.15.0"
byte-strings = "0.2.2"